bench: 
    - tpca
    - tpcc
    - rw_benchmark
graph:
    using_cmd: '6:15:12:14'
    errorbars: 'yerrorbars'
    x_label: 'Clients'
    y_label: 'Latency (ms)'
    y_range: '[1:]'
    x_range: '[0:]'
    output_file: '${txn}_${bench}_client_lat99_log'
    key_location: 'top left'
    log_scale: 1
