bench: 
    - tpca
    - tpcc
graph:
    using_cmd: ($6):($7)
    x_label: 'Clients'
    y_label: 'Throughput (txn/s)'
    y_range: '[0:]'
    x_range: '[0:]'
    output_file: '${txn}_tpca_client_tp.png'
    key_location: 'top left'
