bench: 
    - tpca
    - tpcc
    - rw_benchmark
graph:
    using_cmd: '6:12'
    x_label: 'Clients'
    y_label: 'Latency (ms)'
    y_range: '[0:]'
    x_range: '[0:]'
    output_file: '${txn}_${bench}_client_lat'
    key_location: 'top left'
