bench: 
    - tpca
    - tpcc
    - rw_benchmark
graph:
    using_cmd: '6:($9/$10*100.0)'
    x_label: 'Clients'
    y_label: 'Commit %'
    y_range: '[0:100]'
    x_range: '[0:]'
    y_tics: '0,10'
    output_file: '${txn}_${bench}_client_commitrate'
    key_location: 'bottom left'
