bench: 
    - tpca
    - tpcc
graph:
    using_cmd: '6:13:12:14'
    errorbars: 'yerrorbars'
    x_label: 'Clients'
    y_label: 'Latency (ms)'
    y_range: '[0:]'
    x_range: '[0:]'
    output_file: '${txn}_tpca_client_lat.png'
    key_location: 'top left'
