bench: 
    - rw_benchmark
graph:
    using_cmd: ($6):($7)
    x_label: 'Clients'
    y_label: 'Throughput (txn/s)'
    y_range: '[0:27000]'
    x_range: '[0:]'
    y_tics: '0, 5000'
    output_file: 'rw_${txn}_${bench}_client_tp'
    key_location: 'top left horizontal maxcols 2'
