bench: 
    - tpca
    - tpcc
    - rw_benchmark
output:
    - epslatex
    - png
graph:
    using_cmd: '7:13'
    x_label: 'Throughput (txn/s)'
    y_label: 'Latency (ms)'
    y_range: '[0:]'
    x_range: '[0:]'
    output_file: '${txn}_${bench}_tp_lat'
    key_location: 'top left'

