bench: 
    - tpca
    - tpcc
    - rw_benchmark
graph:
    using_cmd: ($6/100):($13)
    x_label: 'Hundreds of Clients'
    y_label: 'Latency (ms)'
    y_range: '[0:]'
    x_range: '[0:]'
    y_tics: 0, 4000
    output_file: 'tpcc_${txn}_${bench}_client_lat90'
    key_location: 'top left'
