bench: 
    - tpca
    - tpcc
    - rw_benchmark
graph:
    using_cmd: '($6/100):($9/$8)'
    x_label: 'Hundreds of Clients'
    y_label: 'Commit Rate'
    output_file: 'tpcc_${txn}_${bench}_client_commits_attempts'
    key_location: 'center right'
    y_range: '[0:1.1]'
    x_range: '[0:]'
