bench: 
    - tpca
graph:
    using_cmd: '18:7'
    x_label: 'Zipf Coefficient'
    y_label: 'Throughput (txn/s)'
    y_range: '[0:]'
    x_range: '[0:]'
    output_file: '${txn}_${bench}_zipf_tp'
    key_location: 'top left'