bench: 
    - tpca
graph:
    using_cmd: '18:12'
    x_label: 'Zipf Coefficient'
    y_label: 'Latency (ms)'
    y_range: '[0:]'
    x_range: '[0.5:1]'
    output_file: '${txn}_${bench}_zipf_lat'
    key_location: 'top left'
    x_tics: 0,0.25
