bench: 
    - tpca
graph:
    using_cmd: '18:($9/$10*100.0)'
    x_label: 'Zipf Coefficient'
    y_label: '# Commits / # Started'
    y_range: '[0:]'
    x_range: '[0:]'
    output_file: '${txn}_${bench}_zipf_attemptspct'
    key_location: 'bottom left'
