bench: 
    - tpca
graph:
    using_cmd: '18:7'
    x_label: 'Zipf Coefficient'
    y_label: 'Throughput (txn/s)'
    y_range: '[0:]'
    x_range: '[0.5:1]'
    x_tics: 0,0.1
    y_tics: 0,20000
    output_file: 'single_${txn}_${bench}_zipf_tp'
    key_location: 'vertical outside right font ",14" spacing 4'