bench: 
    - tpca
graph:
    using_cmd: '18:14'
    x_label: 'Zipf Coefficient'
    y_label: 'Latency (ms)'
    y_range: '[10:]'
    x_range: '[0.5:1]'
    output_file: '${txn}_${bench}_zipf_lat90'
    key_location: 'top left'
    log_scale: 1
    x_tics: 0,0.25
