host:
    b1: beaker-20
    b2: beaker-21
    b3: beaker-22
    b4: beaker-23
    b5: beaker-24
    b6: beaker-25
    b7: beaker-15
    b8: beaker-16
    b9: beaker-17
    b10: beaker-18
    b11: beaker-19
